### ISSUE TITLE
Browser always asking me to share camera

### ISSUE THREAD

**Issue by CharlesNepote** [moigonzalez/pwa-barcode-scanner#5]
On Firefox 64 / Android, the browser is asking every time I want to use the camera to scan, even if I don't leave the app.

To reproduce:
* go to https://pwascanit.com/ (browser asks to use camera) -> click on "share" button
* click on "history" button
* then click on "Camera" button -> the browser is asking again to use the camera

**Comment by moigonzalez** [comment]
This seems to be the way Firefox functions. There's a bug report in here: https://bugzilla.mozilla.org/show_bug.cgi?id=1250872

It mentions that "There's no equivalent to "Always Allow" in the Android gUM dialog."

**Comment by moigonzalez** [comment]
Great!! Thanks a lot 😄
